source ~/.local/lib/python2.7/site-packages/powerline/bindings/tmux/powerline.conf
# set-option -g default-terminal "screen-256color"
set -g default-terminal "screen-256color"
set -g terminal-overrides ",alacritty:RGB"

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel "xclip -i -sel c"
